name: LegendPractice
version: 1.0
main: tk.legendserver.legendpractice.LegendPractice

author: Magix/KingRainbow44

permissions:
  legend:
    children:
      practice:
        children:
          version:
            default: true
          scoreboard:
            default: true
          kit:
            default: op
          duel:
            default: op

commands:
  setversion:
    description: Sets your playing version! (java|bedrock)
    permission: legend.practice.version
  scoreboard:
    description: Customize your scoreboard!
    permission: legend.practice.scoreboard
  kit:
    description: Give yourself a kit.
    permission: legend.practice.kit
  duel:
    description: Main commmand to duel others!
    permission: legend.practice.duel